# Generated by Django 5.2.1 on 2025-05-29 00:51

import apps.main.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.main.models.document_template_upload_to, verbose_name='Файл шаблона')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizations', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название должности')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizations', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа процесса')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('count_position', models.PositiveIntegerField(verbose_name='Количество этапов согласования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templated', to='main.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Тип процесса',
                'verbose_name_plural': 'Типы процессов',
            },
        ),
        migrations.CreateModel(
            name='ProcessType_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок согласования')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizations', verbose_name='Организация')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.processtype', verbose_name='Тип процесса')),
            ],
            options={
                'verbose_name': 'Порядок согласования',
                'verbose_name_plural': 'Порядки согласования',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('comment', models.TextField(null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_work', 'В работе'), ('approving', 'На согласовании'), ('approved', 'Утвержден'), ('rejected', 'Отклонен'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл документа')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.processtype', verbose_name='Тип процесса')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.processtype_order', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, help_text='Можно указать @username или номер телефона', max_length=50, null=True, verbose_name='Telegram')),
                ('approve', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizations', verbose_name='Организация')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.positions', verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='processtype_order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profiles', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.profiles', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История документа',
                'verbose_name_plural': 'Истории документов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_documents', to='main.profiles', verbose_name='Автор документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.profiles', verbose_name='Получатель документа (Не обязательно)'),
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Поле шаблона',
                'verbose_name_plural': 'Поля шаблонов',
            },
        ),
    ]
