# Generated by Django 5.2.1 on 2025-05-29 06:29

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.main.models.document_upload_to, verbose_name='Файл документа'),
        ),
    ]
