# Generated by Django 5.2.1 on 2025-06-04 06:05

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main.models.document_upload_to, verbose_name='Предпросмотр документа'),
        ),
    ]
