# Generated by Django 5.2.1 on 2025-06-04 08:03

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.AddField(
            model_name='document',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.main.models.document_upload_to, verbose_name='Предпросмотр документа'),
        ),
    ]
