# Generated by Django 5.2.1 on 2025-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_document_image_document_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype_order',
            name='process',
            field=models.CharField(choices=[('approve', 'Согласование'), ('execution', 'Исполнение'), ('regestration', 'Регистрация'), ('acquaintance', 'Ознакомление')], default='approve', max_length=20, verbose_name='Статус документа'),
        ),
    ]
