# Generated by Django 5.2.1 on 2025-06-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_processtype_order_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype_order',
            name='process',
        ),
        migrations.AddField(
            model_name='processtype_order',
            name='status',
            field=models.CharField(choices=[('approve', 'Согласование'), ('execution', 'Исполнение'), ('regestration', 'Регистрация'), ('acquaintance', 'Ознакомление')], default='approve', max_length=20, verbose_name='Процесс'),
        ),
    ]
